name: marp-GitHub-actions

on:
  push:
    branches:
      # create-pdfブランチへのプッシュ時にアーティファクト作成
      - create-pdf/*
      - main

env:
  PDF_CONFIG_FILE: ./98_presentation/pdf/config.json
  PDF_DIR: 98_presentation/pdf
  BRANCH_BASE: create-pdf/

jobs:
  marp-to-pdf:
    name: Create Pdf Job
    runs-on: ubuntu-latest

    steps:
      # stepsへのID付与
      - name: Checkout
        uses: actions/checkout@v2

      # branch名称からファイル名称を取得する
      - name: Extract File Name
        id: extract_branch
        run: |-
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
          echo ${GITHUB_REF#refs/heads/} | sed -e 's/${BRANCH_BASE}//'

      # おまじない及びjson操作コマンドのインストール
      - name: Set Up Linux Command
        run: |-
          sudo apt-get update \
          &&  sudo apt-get upgrade -y \
          &&  sudo apt-get install -y jq

      # config.jsonから設定値を読み取り後続処理に渡す
      - name: Extraction Config
        id: config
        run: |-
          directory=$(cat $PDF_CONFIG_FILE | jq -r .directory)
          output_format=$(cat $PDF_CONFIG_FILE | jq -r .output_format)
          echo "::set-output name=DIR::${directory}"
          echo "::set-output name=FORMAT::${output_format}"

      # PDF関連フォルダのパーミッションの変更
      - name: Change Permission
        run: |-
          chmod -R 777 ${PDF_DIR}/

      # MarpからPDFへのビルド
      - name: Build Marp to PDF
        run: |-
          cd ${PDF_DIR}
          ls -lR
          docker run --rm -u root --init -v $PWD:/home/marp/app/ \
            -e LANG=$LANG marpteam/marp-cli slide.md \
            -o slide.${{steps.config.outputs.FORMAT}}

      # アーティファクトの作成及びアップロード
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output_slide
          path: slide.${{steps.config.outputs.FORMAT}}
