name: marp-GitHub-actions

on:
  push:
    branches:
      # create-pdfブランチへのプッシュ時にアーティファクト作成
      - create-pdf
      - main

env:
  PDF_CONFIG_FILE: ./98_presentation/pdf/config.json

jobs:
  marp-to-pdf:
    name: Create Pdf Job
    runs-on: ubuntu-latest

    steps:
      # stepsへのID付与
      - name: Checkout
        uses: actions/checkout@v2

      # おまじない及びjson操作コマンドのインストール
      - name: Set Up Linux Command
        run: |-
          sudo apt-get update & \
            sudo apt-get upgrade & \
            sudo apt-get install jq

      # config.jsonから設定値を読み取り後続処理に渡す
      - name: Extraction Config
        id: config
        run: |-
          cat $PDF_CONFIG_FILE
          directory=$(cat $PDF_CONFIG_FILE | jq -r .directory)
          output_format=$(cat $PDF_CONFIG_FILE | jq -r .output_format)
          echo "::set-output name=DIR::${directory}"
          echo "::set-output name=FORMAT::${output_format}"

      # MarpからPDFへのビルド
      - name: Build Marp to PDF
        run: |-
          echo "output-dir : ${{steps.config.outputs.DIR}}"
          echo "output-format : ${{steps.config.outputs.DIR}}"
          docker run --rm -u root --init -v $PWD:/home/marp/app/ \
            -e LANG=$LANG marpteam/marp-cli ${{steps.config.outputs.DIR}}/slide.md \
            --${{steps.config.outputs.FORMAT}} \
            -o ${{steps.config.outputs.DIR}}.${{steps.config.outputs.FORMAT}} \

      # アーティファクトの作成及びアップロード
      #- name: Upload Artifact
      #uses: actions/upload-artifact@v2
      #with:
      #name: output_slide
      #path: ${{steps.config.outputs.DIR}}.${{steps.config.outputs.FORMAT}}
